name: Django Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Django
        run: python manage.py migrate

      - name: Run Django tests
        run: python manage.py test
